const analystSteps = [
  "先把商業需求改寫成明確的輸出。",
  "確認一列資料代表什麼（grain）以及需要哪些表格與欄位。",
  "先跑小範圍查詢，再逐步加入條件。",
  "核對列數、NULL、重複值或總額，確認結果可信。",
  "用一句話說明結果、假設與限制。",
];

function question({
  id,
  chapterId,
  unit,
  stage,
  title,
  context,
  task,
  example,
  expected,
  hints,
  skills,
  referenceSql,
  compare = "exact",
  ordered = false,
  readinessDimension,
}) {
  return {
    id,
    chapterId,
    unit,
    stage,
    title,
    context,
    task,
    example,
    expected,
    hints,
    skills,
    referenceSql,
    compare,
    ordered,
    readinessDimension,
    analystSteps,
    reflectionPrompt:
      "請用自己的話寫下：這個結果回答了什麼商業問題？你做了哪一個驗證？",
  };
}

const chapters = [
  {
    id: "ch01",
    order: 1,
    eyebrow: "CHAPTER 1",
    title: "SQL Fundamentals for Analysts",
    subtitle: "拿到正確資料",
    description: "從陌生資料庫安全找表、選欄、篩選、排序、處理 NULL，並讀懂錯誤。",
    readinessDimension: "資料取得與基礎 SQL",
    questions: [
      question({
        id: "ch01-q01",
        chapterId: "ch01",
        unit: "1.1",
        stage: "示範後模仿",
        title: "新到職：確認賣家資料量",
        context: "你剛接手 Olist 資料庫，主管要你先確認賣家主檔的規模。",
        task: "計算 olist.sellers_raw 的總列數，欄位命名為 seller_row_count。",
        example: "相近例子：SELECT COUNT(*) AS order_row_count FROM olist.orders_raw;",
        expected: "1 列、1 欄；欄名為 seller_row_count。",
        hints: ["想像在 Excel 看工作表總共有幾列。", "會用到 COUNT(*) 與 AS。", "資料表是 olist.sellers_raw。"],
        skills: ["SELECT", "COUNT", "AS", "schema"],
        referenceSql: "SELECT COUNT(*) AS seller_row_count FROM olist.sellers_raw",
        readinessDimension: "資料取得與基礎 SQL",
      }),
      question({
        id: "ch01-q02",
        chapterId: "ch01",
        unit: "1.2",
        stage: "相似題",
        title: "相似任務：評論資料量",
        context: "客服主管想知道目前可供分析的評論資料規模。",
        task: "計算 olist.order_reviews_raw 的總列數，欄位命名為 review_row_count。",
        example: "上一題使用 COUNT(*) 計算賣家資料量；這次換成評論表與新的別名。",
        expected: "1 列、1 欄；欄名為 review_row_count。",
        hints: ["沿用上一題的查詢形狀。", "更換資料表與欄位別名。", "表名是 olist.order_reviews_raw。"],
        skills: ["SELECT", "COUNT", "AS", "transfer"],
        referenceSql: "SELECT COUNT(*) AS review_row_count FROM olist.order_reviews_raw",
        readinessDimension: "資料取得與基礎 SQL",
      }),
      question({
        id: "ch01-q03",
        chapterId: "ch01",
        unit: "1.3",
        stage: "條件變形",
        title: "找出最近完成的訂單",
        context: "營運人員要抽查最近送達的訂單，確認資料是否持續更新。",
        task: "從 orders_raw 選出 order_id、order_status、order_purchase_timestamp；只保留 delivered，最新下單時間排前面，取 10 列。",
        example: "相近例子：用 WHERE 選狀態、ORDER BY ... DESC 排最新、LIMIT 控制抽樣。",
        expected: "3 欄、最多 10 列；全部為 delivered 且日期由新到舊。",
        hints: ["先選欄位，再決定資料表。", "用 WHERE order_status = 'delivered'。", "ORDER BY order_purchase_timestamp DESC，最後 LIMIT 10。"],
        skills: ["WHERE", "ORDER BY", "DESC", "LIMIT"],
        referenceSql: "SELECT order_id, order_status, order_purchase_timestamp FROM olist.orders_raw WHERE order_status = 'delivered' ORDER BY order_purchase_timestamp DESC LIMIT 10",
        ordered: true,
        readinessDimension: "資料取得與基礎 SQL",
      }),
      question({
        id: "ch01-q04",
        chapterId: "ch01",
        unit: "1.4",
        stage: "資料品質",
        title: "找出尚未記錄送達日的訂單",
        context: "客服正在追查沒有實際送達日期的訂單，需要先抽樣確認狀態。",
        task: "選出 order_id、order_status、order_delivered_customer_date；只保留送達日期為 NULL 的資料，依購買時間由新到舊取 15 列。",
        example: "缺少值不能用 = NULL，要使用 IS NULL。",
        expected: "3 欄、最多 15 列；送達日期全部為 NULL。",
        hints: ["NULL 代表未知或缺少。", "條件是 order_delivered_customer_date IS NULL。", "排序欄仍可使用未顯示在結果中的 order_purchase_timestamp。"],
        skills: ["NULL", "IS NULL", "ORDER BY", "validation"],
        referenceSql: "SELECT order_id, order_status, order_delivered_customer_date FROM olist.orders_raw WHERE order_delivered_customer_date IS NULL ORDER BY order_purchase_timestamp DESC LIMIT 15",
        ordered: true,
        readinessDimension: "資料取得與基礎 SQL",
      }),
      question({
        id: "ch01-q05",
        chapterId: "ch01",
        unit: "1.5",
        stage: "商業分類",
        title: "把評論分成服務等級",
        context: "客服主管不想逐筆看 1–5 分，希望先分成負面、中立與正面。",
        task: "選出 review_id、review_score，使用 CASE 建立 review_group：1–2 為 negative、3 為 neutral、4–5 為 positive；依 review_score 排序後取 20 列。",
        example: "CASE WHEN 像 Excel IF：條件成立就回傳指定分類。",
        expected: "3 欄；review_group 與 review_score 的規則一致。",
        hints: ["先寫兩個 WHEN，最後用 ELSE。", "1–2 可以寫 review_score <= 2。", "CASE 結束要使用 END AS review_group。"],
        skills: ["CASE WHEN", "business rules", "alias"],
        referenceSql: "SELECT review_id, review_score, CASE WHEN review_score <= 2 THEN 'negative' WHEN review_score = 3 THEN 'neutral' ELSE 'positive' END AS review_group FROM olist.order_reviews_raw ORDER BY review_score, review_id LIMIT 20",
        ordered: true,
        readinessDimension: "資料取得與基礎 SQL",
      }),
      question({
        id: "ch01-q06",
        chapterId: "ch01",
        unit: "1.6",
        stage: "章末白紙挑戰",
        title: "高金額訂單明細抽查",
        context: "稽核人員要查看價格至少 1,000 的訂單明細，優先檢查最高金額。",
        task: "從 order_items_raw 選出 order_id、product_id、seller_id、price、freight_value；price >= 1000，依 price 由高到低取 12 列。",
        example: "這是 Chapter 1 綜合題；請自己決定 SELECT、WHERE、ORDER BY 與 LIMIT 的順序。",
        expected: "5 欄、最多 12 列；price 都至少 1,000 且由高到低。",
        hints: ["先把一句需求拆成欄位、篩選、排序、列數。", "金額條件使用 >=。", "完整表名為 olist.order_items_raw。"],
        skills: ["SELECT", "WHERE", "ORDER BY", "LIMIT", "independent"],
        referenceSql: "SELECT order_id, product_id, seller_id, price, freight_value FROM olist.order_items_raw WHERE price >= 1000 ORDER BY price DESC, order_id LIMIT 12",
        ordered: true,
        readinessDimension: "資料取得與基礎 SQL",
      }),
    ],
  },
  {
    id: "ch02",
    order: 2,
    eyebrow: "CHAPTER 2",
    title: "JOIN & Relational Database",
    subtitle: "正確串接公司資料",
    description: "先確認 grain 與 key，再完成 INNER／LEFT／多表 JOIN，並防止金額或列數被放大。",
    readinessDimension: "JOIN 與資料粒度",
    questions: [
      question({
        id: "ch02-q01", chapterId: "ch02", unit: "2.1", stage: "示範後模仿", title: "把訂單接到客戶州別",
        context: "營運主管需要知道每張訂單屬於哪個客戶州別。",
        task: "INNER JOIN orders_raw 與 customers_raw，選出 order_id、order_status、customer_state，依 order_id 取前 20 列。",
        example: "SAP 類比：用 customer_id 把訂單抬頭接到客戶主檔。",
        expected: "3 欄、20 列；每列都有 customer_state。",
        hints: ["先決定左表 orders_raw。", "兩表共同 key 是 customer_id。", "使用表別名避免欄名不清楚。"],
        skills: ["INNER JOIN", "key", "table alias", "grain"],
        referenceSql: "SELECT o.order_id, o.order_status, c.customer_state FROM olist.orders_raw o INNER JOIN olist.customers_raw c ON o.customer_id = c.customer_id ORDER BY o.order_id LIMIT 20",
        ordered: true, readinessDimension: "JOIN 與資料粒度",
      }),
      question({
        id: "ch02-q02", chapterId: "ch02", unit: "2.2", stage: "相似題", title: "把訂單明細接到賣家州別",
        context: "採購團隊要抽查高價品項來自哪個賣家州別。",
        task: "JOIN order_items_raw 與 sellers_raw，選出 order_id、product_id、price、seller_state；依 price 由高到低取 20 列。",
        example: "上一題以 customer_id 串接；這題改用 seller_id。",
        expected: "4 欄、20 列；價格由高到低。",
        hints: ["先說出兩張表各一列代表什麼。", "共同 key 是 seller_id。", "排序欄是 order_items_raw.price。"],
        skills: ["INNER JOIN", "seller_id", "ORDER BY", "transfer"],
        referenceSql: "SELECT oi.order_id, oi.product_id, oi.price, s.seller_state FROM olist.order_items_raw oi INNER JOIN olist.sellers_raw s ON oi.seller_id = s.seller_id ORDER BY oi.price DESC, oi.order_id LIMIT 20",
        ordered: true, readinessDimension: "JOIN 與資料粒度",
      }),
      question({
        id: "ch02-q03", chapterId: "ch02", unit: "2.3", stage: "保留缺漏", title: "找出沒有評論的訂單",
        context: "客戶體驗團隊想知道哪些已送達訂單沒有評論。",
        task: "從 delivered 訂單出發，LEFT JOIN reviews，找出 review 的 order_id 為 NULL；輸出訂單 order_id 與購買時間，最新 20 筆。",
        example: "LEFT JOIN 保留左表全部資料，再用右表 key IS NULL 找未配對。",
        expected: "2 欄、最多 20 列；全部是沒有評論配對的 delivered 訂單。",
        hints: ["左表必須是 orders_raw。", "ON 使用 order_id。", "WHERE 同時包含 delivered 與右表 order_id IS NULL。"],
        skills: ["LEFT JOIN", "anti-join", "NULL", "missing records"],
        referenceSql: "SELECT o.order_id, o.order_purchase_timestamp FROM olist.orders_raw o LEFT JOIN olist.order_reviews_raw r ON o.order_id = r.order_id WHERE o.order_status = 'delivered' AND r.order_id IS NULL ORDER BY o.order_purchase_timestamp DESC LIMIT 20",
        ordered: true, readinessDimension: "JOIN 與資料粒度",
      }),
      question({
        id: "ch02-q04", chapterId: "ch02", unit: "2.4", stage: "多表串接", title: "商品品類英文名稱",
        context: "主管看不懂葡萄牙文品類，需要可讀的英文品類抽樣。",
        task: "從 order_items_raw 接 products_raw，再 LEFT JOIN translation；選出 order_id、product_id、product_category_name_english，依 order_id 取 25 列。",
        example: "先用 product_id 接商品，再用 product_category_name 接翻譯對照表。",
        expected: "3 欄、25 列；沒有翻譯的品類仍應保留。",
        hints: ["第一個 JOIN key 是 product_id。", "翻譯表要用 LEFT JOIN。", "第二個 key 是 product_category_name。"],
        skills: ["multiple JOINs", "lookup table", "LEFT JOIN", "COALESCE awareness"],
        referenceSql: "SELECT oi.order_id, oi.product_id, t.product_category_name_english FROM olist.order_items_raw oi INNER JOIN olist.products_raw p ON oi.product_id = p.product_id LEFT JOIN olist.product_category_translation_raw t ON p.product_category_name = t.product_category_name ORDER BY oi.order_id, oi.order_item_id LIMIT 25",
        ordered: true, readinessDimension: "JOIN 與資料粒度",
      }),
      question({
        id: "ch02-q05", chapterId: "ch02", unit: "2.5", stage: "JOIN 驗證", title: "確認 JOIN 後一張訂單變幾列",
        context: "財務報表金額突然變大，你要先證明訂單接明細後會因一對多關係增加列數。",
        task: "JOIN orders_raw 與 order_items_raw，依 order_id 分組，找出 item_row_count > 1 的訂單；輸出 order_id、item_row_count，最多 20 筆，筆數高的在前。",
        example: "JOIN 前先問 grain：orders 一列一單，items 一列一個品項。",
        expected: "2 欄；item_row_count 全部大於 1。",
        hints: ["JOIN 後以 order_id GROUP BY。", "COUNT(*) AS item_row_count。", "群組後條件使用 HAVING。"],
        skills: ["JOIN duplication", "GROUP BY", "HAVING", "reconciliation"],
        referenceSql: "SELECT o.order_id, COUNT(*) AS item_row_count FROM olist.orders_raw o INNER JOIN olist.order_items_raw oi ON o.order_id = oi.order_id GROUP BY o.order_id HAVING COUNT(*) > 1 ORDER BY item_row_count DESC, o.order_id LIMIT 20",
        ordered: true, readinessDimension: "JOIN 與資料粒度",
      }),
      question({
        id: "ch02-q06", chapterId: "ch02", unit: "2.6", stage: "章末白紙挑戰", title: "高營收賣家與所在地",
        context: "供應鏈主管想先看到商品銷售額最高的賣家及所在州。",
        task: "JOIN order_items_raw 與 sellers_raw；依 seller_id、seller_state 分組，計算 SUM(price) 為 item_revenue，取前 10 名。",
        example: "請先寫下 grain、key 與 metric，再開始 SQL。",
        expected: "3 欄、10 列；item_revenue 由高到低。",
        hints: ["一個賣家會有多筆訂單明細。", "以 seller_id、seller_state 分組。", "item_revenue = SUM(price)。"],
        skills: ["JOIN", "aggregation", "grain", "business metric", "independent"],
        referenceSql: "SELECT oi.seller_id, s.seller_state, SUM(oi.price) AS item_revenue FROM olist.order_items_raw oi INNER JOIN olist.sellers_raw s ON oi.seller_id = s.seller_id GROUP BY oi.seller_id, s.seller_state ORDER BY item_revenue DESC, oi.seller_id LIMIT 10",
        ordered: true, readinessDimension: "JOIN 與資料粒度",
      }),
    ],
  },
  {
    id: "ch03", order: 3, eyebrow: "CHAPTER 3", title: "Advanced Analytical SQL", subtitle: "計算 KPI、排名與趨勢",
    description: "使用彙總、Subquery、CTE 與 Window Functions，把資料轉成可比較的指標。", readinessDimension: "分析型 SQL",
    questions: [
      question({id:"ch03-q01",chapterId:"ch03",unit:"3.1",stage:"示範後模仿",title:"付款方式結構",context:"財務想了解各付款方式的交易筆數與金額。",task:"依 payment_type 分組，計算 payment_count 與 total_payment_value；金額由高到低。",example:"GROUP BY 像 Excel 樞紐分析表：每個付款方式一列。",expected:"每種 payment_type 一列，包含筆數與總金額。",hints:["選 payment_type。","COUNT(*) 與 SUM(payment_value)。","GROUP BY payment_type。"],skills:["GROUP BY","COUNT","SUM","metric"],referenceSql:"SELECT payment_type, COUNT(*) AS payment_count, SUM(payment_value) AS total_payment_value FROM olist.order_payments_raw GROUP BY payment_type ORDER BY total_payment_value DESC, payment_type",ordered:true,readinessDimension:"分析型 SQL"}),
      question({id:"ch03-q02",chapterId:"ch03",unit:"3.2",stage:"相似題",title:"訂單狀態分布",context:"營運主管要比較不同訂單狀態的數量與占比前置資料。",task:"依 order_status 分組，計算 order_count；數量由高到低。",example:"沿用付款方式彙總的形狀，改成訂單狀態與 COUNT。",expected:"每個狀態一列，order_count 由高到低。",hints:["一列代表一種 order_status。","使用 COUNT(*)。","GROUP BY 與 ORDER BY。"],skills:["GROUP BY","COUNT","transfer"],referenceSql:"SELECT order_status, COUNT(*) AS order_count FROM olist.orders_raw GROUP BY order_status ORDER BY order_count DESC, order_status",ordered:true,readinessDimension:"分析型 SQL"}),
      question({id:"ch03-q03",chapterId:"ch03",unit:"3.3",stage:"CTE 分步",title:"每月已送達訂單數",context:"營運會議需要月度趨勢，不希望一段查詢難以驗證。",task:"使用 CTE 先取 delivered 訂單與月份，再按 month 分組計算 delivered_order_count，月份由舊到新。",example:"CTE 是具名的中繼步驟，可先單獨檢查。",expected:"每月一列；月份與訂單數由舊到新。",hints:["DATE_TRUNC('month', order_purchase_timestamp)。","CTE 中只保留 delivered。","外層 GROUP BY month。"],skills:["CTE","DATE_TRUNC","GROUP BY","trend"],referenceSql:"WITH delivered_orders AS (SELECT DATE_TRUNC('month', order_purchase_timestamp) AS month FROM olist.orders_raw WHERE order_status = 'delivered') SELECT month, COUNT(*) AS delivered_order_count FROM delivered_orders GROUP BY month ORDER BY month",ordered:true,readinessDimension:"分析型 SQL"}),
      question({id:"ch03-q04",chapterId:"ch03",unit:"3.4",stage:"Subquery",title:"高於平均售價的品項",context:"稽核想抽查價格高於全體平均的訂單品項。",task:"使用 Subquery 計算平均 price，選出高於平均的 order_id、product_id、price；價格由高到低取 20 列。",example:"內層先算一個平均值，外層用它做篩選。",expected:"3 欄、20 列；全部高於全表平均售價。",hints:["WHERE price > (...)。","括號內 SELECT AVG(price)。","最後 ORDER BY price DESC LIMIT 20。"],skills:["Subquery","AVG","comparison"],referenceSql:"SELECT order_id, product_id, price FROM olist.order_items_raw WHERE price > (SELECT AVG(price) FROM olist.order_items_raw) ORDER BY price DESC, order_id LIMIT 20",ordered:true,readinessDimension:"分析型 SQL"}),
      question({id:"ch03-q05",chapterId:"ch03",unit:"3.5",stage:"Window Ranking",title:"各付款方式中的高額付款排名",context:"財務想在每種付款方式內查看最高付款紀錄。",task:"使用 ROW_NUMBER()，依 payment_type 分區、payment_value 由高到低排名；每種付款方式保留前 3 名。",example:"Window Function 不會像 GROUP BY 把明細折疊。",expected:"每個 payment_type 最多 3 列，payment_rank 為 1–3。",hints:["先在 CTE 算 ROW_NUMBER。","PARTITION BY payment_type。","外層 WHERE payment_rank <= 3。"],skills:["ROW_NUMBER","OVER","PARTITION BY","Top N"],referenceSql:"WITH ranked AS (SELECT payment_type, order_id, payment_value, ROW_NUMBER() OVER (PARTITION BY payment_type ORDER BY payment_value DESC, order_id) AS payment_rank FROM olist.order_payments_raw) SELECT payment_type, order_id, payment_value, payment_rank FROM ranked WHERE payment_rank <= 3 ORDER BY payment_type, payment_rank",ordered:true,readinessDimension:"分析型 SQL"}),
      question({id:"ch03-q06",chapterId:"ch03",unit:"3.6",stage:"章末白紙挑戰",title:"月營收與月增率",context:"主管要判斷營收趨勢，並比較每月與上月差異。",task:"以 order_items 的 price 計算月營收；使用 CTE 與 LAG 產出 month、revenue、previous_month_revenue、growth_rate，月份由舊到新。",example:"先得到每月一列，再在下一層使用 LAG。",expected:"每月一列；第一月前期值為 NULL，其後有成長率。",hints:["先把 orders 與 items JOIN。","CTE 內依 DATE_TRUNC 月份 SUM(price)。","growth_rate = (revenue - previous) / previous。"],skills:["CTE","LAG","growth rate","JOIN","independent"],referenceSql:"WITH monthly AS (SELECT DATE_TRUNC('month', o.order_purchase_timestamp) AS month, SUM(oi.price) AS revenue FROM olist.orders_raw o INNER JOIN olist.order_items_raw oi ON o.order_id = oi.order_id GROUP BY 1), compared AS (SELECT month, revenue, LAG(revenue) OVER (ORDER BY month) AS previous_month_revenue FROM monthly) SELECT month, revenue, previous_month_revenue, ROUND((revenue - previous_month_revenue) / NULLIF(previous_month_revenue, 0) * 100, 2) AS growth_rate FROM compared ORDER BY month",ordered:true,readinessDimension:"分析型 SQL"}),
    ],
  },
  {
    id:"ch04",order:4,eyebrow:"CHAPTER 4",title:"SQL Business Analysis",subtitle:"解決商業問題",description:"不預告要用哪個指令；由需求出發定義 KPI、驗證結果並提出有界線的洞察。",readinessDimension:"商業分析與驗證",
    questions:[
      question({id:"ch04-q01",chapterId:"ch04",unit:"4.1",stage:"KPI 定義",title:"各州準時交貨率",context:"供應鏈主管要比較客戶州別的 On-Time Delivery。",task:"只看 delivered 且有實際與預計日期的訂單；按 customer_state 計算 delivered_orders 與 on_time_rate，至少 100 單，準時率低的在前。",example:"先定義分母、分子、範圍與日期，再寫 SQL。",expected:"每州一列；on_time_rate 是百分比。",hints:["orders JOIN customers。","準時條件：實際送達 <= 預計送達。","AVG(CASE WHEN ... THEN 1.0 ELSE 0 END) * 100。"],skills:["KPI definition","CASE","AVG","JOIN","scope"],referenceSql:"SELECT c.customer_state, COUNT(*) AS delivered_orders, ROUND(AVG(CASE WHEN o.order_delivered_customer_date <= o.order_estimated_delivery_date THEN 1.0 ELSE 0 END) * 100, 2) AS on_time_rate FROM olist.orders_raw o INNER JOIN olist.customers_raw c ON o.customer_id = c.customer_id WHERE o.order_status = 'delivered' AND o.order_delivered_customer_date IS NOT NULL AND o.order_estimated_delivery_date IS NOT NULL GROUP BY c.customer_state HAVING COUNT(*) >= 100 ORDER BY on_time_rate, c.customer_state",ordered:true,readinessDimension:"商業分析與驗證"}),
      question({id:"ch04-q02",chapterId:"ch04",unit:"4.2",stage:"相似 KPI",title:"賣家層級的遲交風險",context:"營運想找出訂單量夠大、遲交率偏高的賣家。",task:"將 delivered 訂單接 items；依 seller_id 計算 order_count 與 late_rate，至少 50 個不同訂單，遲交率高的前 15 名。",example:"沿用準時率概念，但注意一張訂單可能多個品項，要 COUNT(DISTINCT order_id)。",expected:"3 欄、15 列；order_count 至少 50。",hints:["orders JOIN items。","分母使用 DISTINCT order_id。","遲交條件是實際日期 > 預計日期。"],skills:["KPI","COUNT DISTINCT","JOIN duplication","risk"],referenceSql:"SELECT oi.seller_id, COUNT(DISTINCT o.order_id) AS order_count, ROUND(COUNT(DISTINCT CASE WHEN o.order_delivered_customer_date > o.order_estimated_delivery_date THEN o.order_id END)::numeric / NULLIF(COUNT(DISTINCT o.order_id), 0) * 100, 2) AS late_rate FROM olist.orders_raw o INNER JOIN olist.order_items_raw oi ON o.order_id = oi.order_id WHERE o.order_status = 'delivered' AND o.order_delivered_customer_date IS NOT NULL AND o.order_estimated_delivery_date IS NOT NULL GROUP BY oi.seller_id HAVING COUNT(DISTINCT o.order_id) >= 50 ORDER BY late_rate DESC, order_count DESC, oi.seller_id LIMIT 15",ordered:true,readinessDimension:"商業分析與驗證"}),
      question({id:"ch04-q03",chapterId:"ch04",unit:"4.3",stage:"客戶分析",title:"重複購買客戶與訂單數",context:"Customer team 想知道哪些真實客戶曾多次下單。",task:"JOIN customers 與 orders，依 customer_unique_id 計算 order_count；只保留超過 1 單的客戶，前 20 名。",example:"customer_id 每張訂單不同；跨訂單辨識同一人要使用 customer_unique_id。",expected:"2 欄；order_count 全部大於 1。",hints:["customers 是客戶識別來源。","以 customer_unique_id GROUP BY。","HAVING COUNT(*) > 1。"],skills:["customer grain","HAVING","repeat customer"],referenceSql:"SELECT c.customer_unique_id, COUNT(*) AS order_count FROM olist.customers_raw c INNER JOIN olist.orders_raw o ON c.customer_id = o.customer_id GROUP BY c.customer_unique_id HAVING COUNT(*) > 1 ORDER BY order_count DESC, c.customer_unique_id LIMIT 20",ordered:true,readinessDimension:"商業分析與驗證"}),
      question({id:"ch04-q04",chapterId:"ch04",unit:"4.4",stage:"資料品質",title:"檢查重複付款序號",context:"財務報表前要確認同一訂單的 payment_sequential 是否重複。",task:"依 order_id、payment_sequential 分組，找出 duplicate_count > 1 的組合；重複筆數高的在前。",example:"先定義什麼欄位組合應該唯一，再做 GROUP BY 對帳。",expected:"3 欄；若資料乾淨可能回傳 0 列。",hints:["唯一性組合有兩個欄位。","COUNT(*) AS duplicate_count。","HAVING COUNT(*) > 1。"],skills:["data quality","duplicate","reconciliation"],referenceSql:"SELECT order_id, payment_sequential, COUNT(*) AS duplicate_count FROM olist.order_payments_raw GROUP BY order_id, payment_sequential HAVING COUNT(*) > 1 ORDER BY duplicate_count DESC, order_id, payment_sequential",ordered:true,readinessDimension:"商業分析與驗證"}),
      question({id:"ch04-q05",chapterId:"ch04",unit:"4.5",stage:"洞察與限制",title:"遲交與評論分數",context:"主管懷疑遲交會降低評分，但你需要先提供描述性證據，不能直接宣稱因果。",task:"把 delivered 訂單分成 on_time／late，JOIN reviews，計算每組 review_count 與 avg_review_score。",example:"查詢只能顯示關聯；結論需註明不能證明因果。",expected:"每個 delivery_group 一列，包含評論數與平均分數。",hints:["CASE 建 delivery_group。","orders JOIN reviews。","GROUP BY CASE 結果。"],skills:["insight","assumption","limitation","CASE","AVG"],referenceSql:"SELECT CASE WHEN o.order_delivered_customer_date <= o.order_estimated_delivery_date THEN 'on_time' ELSE 'late' END AS delivery_group, COUNT(*) AS review_count, ROUND(AVG(r.review_score), 2) AS avg_review_score FROM olist.orders_raw o INNER JOIN olist.order_reviews_raw r ON o.order_id = r.order_id WHERE o.order_status = 'delivered' AND o.order_delivered_customer_date IS NOT NULL AND o.order_estimated_delivery_date IS NOT NULL GROUP BY 1 ORDER BY delivery_group",ordered:true,readinessDimension:"商業分析與驗證"}),
      question({id:"ch04-q06",chapterId:"ch04",unit:"4.6",stage:"章末商業 Case",title:"哪些品類帶動已送達營收",context:"主管要知道已送達訂單中營收最高的英文商品品類。",task:"串接 orders、items、products、translation；計算 item_revenue 與 order_count，取前 15 個品類，沒有翻譯以 'untranslated' 顯示。",example:"先寫 KPI 定義：item_revenue 是 SUM(price)，不是 profit。",expected:"3 欄、15 列；item_revenue 由高到低。",hints:["以 orders 過濾 delivered。","translation 使用 LEFT JOIN＋COALESCE。","order_count 用 COUNT(DISTINCT order_id)。"],skills:["business case","multiple JOINs","KPI","COALESCE","validation"],referenceSql:"SELECT COALESCE(t.product_category_name_english, 'untranslated') AS category, SUM(oi.price) AS item_revenue, COUNT(DISTINCT o.order_id) AS order_count FROM olist.orders_raw o INNER JOIN olist.order_items_raw oi ON o.order_id = oi.order_id INNER JOIN olist.products_raw p ON oi.product_id = p.product_id LEFT JOIN olist.product_category_translation_raw t ON p.product_category_name = t.product_category_name WHERE o.order_status = 'delivered' GROUP BY 1 ORDER BY item_revenue DESC, category LIMIT 15",ordered:true,readinessDimension:"商業分析與驗證"}),
    ],
  },
  {
    id:"ch05",order:5,eyebrow:"CHAPTER 5",title:"Entry-Level Analyst Simulation",subtitle:"像初級分析師一樣工作",description:"接模糊需求、拆解範圍、建立可重跑查詢、驗證、寫主管摘要並接受工作模擬評量。",readinessDimension:"工作模擬與溝通",
    questions:[
      question({id:"ch05-q01",chapterId:"ch05",unit:"5.1",stage:"需求拆解",title:"Q2 遲交是否增加",context:"主管只說：『Q2 遲交好像增加了，請查一下。』你需要把它改成可驗證的月度問題。",task:"只看 delivered；按月份計算 delivered_orders、late_orders、late_rate，輸出 2018-01 至 2018-06，月份由舊到新。",example:"先明確定義 Q2、遲交、分母與比較期間。",expected:"2018 上半年每月一列，包含完整 KPI 元件。",hints:["日期範圍使用 >= 2018-01-01 且 < 2018-07-01。","COUNT(CASE WHEN ...)。","late_rate 分母是 delivered 訂單。"],skills:["requirement intake","KPI","date scope","validation"],referenceSql:"SELECT DATE_TRUNC('month', order_purchase_timestamp) AS month, COUNT(*) AS delivered_orders, COUNT(CASE WHEN order_delivered_customer_date > order_estimated_delivery_date THEN 1 END) AS late_orders, ROUND(COUNT(CASE WHEN order_delivered_customer_date > order_estimated_delivery_date THEN 1 END)::numeric / NULLIF(COUNT(*), 0) * 100, 2) AS late_rate FROM olist.orders_raw WHERE order_status = 'delivered' AND order_purchase_timestamp >= '2018-01-01' AND order_purchase_timestamp < '2018-07-01' AND order_delivered_customer_date IS NOT NULL AND order_estimated_delivery_date IS NOT NULL GROUP BY 1 ORDER BY month",ordered:true,readinessDimension:"工作模擬與溝通"}),
      question({id:"ch05-q02",chapterId:"ch05",unit:"5.2",stage:"相似診斷",title:"Q2 遲交集中在哪些州",context:"主管看到整體趨勢後，追問問題集中在哪些客戶州別。",task:"計算 2018 Q2 各 customer_state 的 delivered_orders、late_orders、late_rate；至少 100 單，遲交率高的前 10 名。",example:"沿用上一題 KPI，新增 customers JOIN 與州別分組。",expected:"4 欄、最多 10 列；單量至少 100。",hints:["orders JOIN customers。","日期範圍是 2018-04-01 到 2018-07-01 前。","HAVING COUNT(*) >= 100。"],skills:["drill-down","JOIN","KPI transfer","stakeholder follow-up"],referenceSql:"SELECT c.customer_state, COUNT(*) AS delivered_orders, COUNT(CASE WHEN o.order_delivered_customer_date > o.order_estimated_delivery_date THEN 1 END) AS late_orders, ROUND(COUNT(CASE WHEN o.order_delivered_customer_date > o.order_estimated_delivery_date THEN 1 END)::numeric / NULLIF(COUNT(*), 0) * 100, 2) AS late_rate FROM olist.orders_raw o INNER JOIN olist.customers_raw c ON o.customer_id = c.customer_id WHERE o.order_status = 'delivered' AND o.order_purchase_timestamp >= '2018-04-01' AND o.order_purchase_timestamp < '2018-07-01' AND o.order_delivered_customer_date IS NOT NULL AND o.order_estimated_delivery_date IS NOT NULL GROUP BY c.customer_state HAVING COUNT(*) >= 100 ORDER BY late_rate DESC, delivered_orders DESC, c.customer_state LIMIT 10",ordered:true,readinessDimension:"工作模擬與溝通"}),
      question({id:"ch05-q03",chapterId:"ch05",unit:"5.3",stage:"根因候選",title:"高遲交州的賣家風險",context:"你需要把地區發現往可行動的賣家層級拆解。",task:"針對 customer_state = 'SP' 的 2018 Q2 delivered 訂單，依 seller_id 計算 order_count 與 late_rate；至少 20 單，取遲交率前 15 名。",example:"這是診斷候選，不代表賣家一定造成遲交；需在結論寫限制。",expected:"3 欄、最多 15 列；order_count 至少 20。",hints:["orders → customers 與 orders → items。","COUNT(DISTINCT order_id) 防止多品項放大。","分子也要 DISTINCT order_id。"],skills:["root-cause candidate","COUNT DISTINCT","limitation","seller performance"],referenceSql:"SELECT oi.seller_id, COUNT(DISTINCT o.order_id) AS order_count, ROUND(COUNT(DISTINCT CASE WHEN o.order_delivered_customer_date > o.order_estimated_delivery_date THEN o.order_id END)::numeric / NULLIF(COUNT(DISTINCT o.order_id), 0) * 100, 2) AS late_rate FROM olist.orders_raw o INNER JOIN olist.customers_raw c ON o.customer_id = c.customer_id INNER JOIN olist.order_items_raw oi ON o.order_id = oi.order_id WHERE o.order_status = 'delivered' AND c.customer_state = 'SP' AND o.order_purchase_timestamp >= '2018-04-01' AND o.order_purchase_timestamp < '2018-07-01' AND o.order_delivered_customer_date IS NOT NULL AND o.order_estimated_delivery_date IS NOT NULL GROUP BY oi.seller_id HAVING COUNT(DISTINCT o.order_id) >= 20 ORDER BY late_rate DESC, order_count DESC, oi.seller_id LIMIT 15",ordered:true,readinessDimension:"工作模擬與溝通"}),
      question({id:"ch05-q04",chapterId:"ch05",unit:"5.4",stage:"正式驗證",title:"交付前的對帳表",context:"主管摘要送出前，你需要一張按月的對帳表證明分子不超過分母、日期缺漏可見。",task:"按月份輸出 delivered_orders、complete_date_orders、late_orders；涵蓋 2018 上半年。",example:"專業分析師會保留驗證查詢，而不是只留下最後一張漂亮報表。",expected:"每月一列；complete_date_orders <= delivered_orders，late_orders <= complete_date_orders。",hints:["三個 COUNT 使用不同 CASE。","月份來自 order_purchase_timestamp。","只過濾 delivered 與日期範圍，不先排除 NULL。"],skills:["validation","reconciliation","audit trail"],referenceSql:"SELECT DATE_TRUNC('month', order_purchase_timestamp) AS month, COUNT(*) AS delivered_orders, COUNT(CASE WHEN order_delivered_customer_date IS NOT NULL AND order_estimated_delivery_date IS NOT NULL THEN 1 END) AS complete_date_orders, COUNT(CASE WHEN order_delivered_customer_date > order_estimated_delivery_date THEN 1 END) AS late_orders FROM olist.orders_raw WHERE order_status = 'delivered' AND order_purchase_timestamp >= '2018-01-01' AND order_purchase_timestamp < '2018-07-01' GROUP BY 1 ORDER BY month",ordered:true,readinessDimension:"工作模擬與溝通"}),
      question({id:"ch05-q05",chapterId:"ch05",unit:"5.5",stage:"作品集證據",title:"建立可重跑的主管摘要資料集",context:"你要把分析整理成作品集可重跑的核心結果。",task:"使用 CTE 產出 2018 Q2 各州遲交率、平均評論分數與訂單數；至少 100 單，遲交率高的前 10 名。",example:"查詢要分步命名，讓 reviewer 能逐段執行與檢查。",expected:"customer_state、order_count、late_rate、avg_review_score 四欄。",hints:["第一個 CTE 建立訂單層級資料。","reviews 可能缺少，使用 LEFT JOIN。","外層州別彙總。"],skills:["portfolio SQL","CTE","reviewability","executive dataset"],referenceSql:"WITH order_level AS (SELECT o.order_id, c.customer_state, CASE WHEN o.order_delivered_customer_date > o.order_estimated_delivery_date THEN 1 ELSE 0 END AS is_late, r.review_score FROM olist.orders_raw o INNER JOIN olist.customers_raw c ON o.customer_id = c.customer_id LEFT JOIN olist.order_reviews_raw r ON o.order_id = r.order_id WHERE o.order_status = 'delivered' AND o.order_purchase_timestamp >= '2018-04-01' AND o.order_purchase_timestamp < '2018-07-01' AND o.order_delivered_customer_date IS NOT NULL AND o.order_estimated_delivery_date IS NOT NULL) SELECT customer_state, COUNT(DISTINCT order_id) AS order_count, ROUND(AVG(is_late) * 100, 2) AS late_rate, ROUND(AVG(review_score), 2) AS avg_review_score FROM order_level GROUP BY customer_state HAVING COUNT(DISTINCT order_id) >= 100 ORDER BY late_rate DESC, customer_state LIMIT 10",ordered:true,readinessDimension:"工作模擬與溝通"}),
      question({id:"ch05-q06",chapterId:"ch05",unit:"5.6",stage:"Entry-Level 最終模擬",title:"完整供應鏈績效 Case",context:"最終任務：向主管說明 2018 Q2 遲交、營收與評分的交叉情況，並留下可驗證的 SQL。",task:"按 customer_state 產出 order_count、item_revenue、late_rate、avg_review_score；至少 100 單，item_revenue 由高到低取 10 州。",example:"完成後的反思必須分開寫：證據、推論、限制、下一步。",expected:"5 欄、10 列；使用正確 grain 避免 reviews 與 items 造成重複。",hints:["先各自在訂單層級彙總 items 與 reviews，再串回 orders。","一張訂單先變成一列，再做州別 KPI。","最後驗證 order_count 與營收是否合理。"],skills:["job simulation","grain control","multi-CTE","KPI","executive communication","independent"],referenceSql:"WITH item_totals AS (SELECT order_id, SUM(price) AS item_revenue FROM olist.order_items_raw GROUP BY order_id), review_scores AS (SELECT order_id, AVG(review_score) AS review_score FROM olist.order_reviews_raw GROUP BY order_id), order_level AS (SELECT o.order_id, c.customer_state, it.item_revenue, CASE WHEN o.order_delivered_customer_date > o.order_estimated_delivery_date THEN 1 ELSE 0 END AS is_late, rs.review_score FROM olist.orders_raw o INNER JOIN olist.customers_raw c ON o.customer_id = c.customer_id INNER JOIN item_totals it ON o.order_id = it.order_id LEFT JOIN review_scores rs ON o.order_id = rs.order_id WHERE o.order_status = 'delivered' AND o.order_purchase_timestamp >= '2018-04-01' AND o.order_purchase_timestamp < '2018-07-01' AND o.order_delivered_customer_date IS NOT NULL AND o.order_estimated_delivery_date IS NOT NULL) SELECT customer_state, COUNT(*) AS order_count, SUM(item_revenue) AS item_revenue, ROUND(AVG(is_late) * 100, 2) AS late_rate, ROUND(AVG(review_score), 2) AS avg_review_score FROM order_level GROUP BY customer_state HAVING COUNT(*) >= 100 ORDER BY item_revenue DESC, customer_state LIMIT 10",ordered:true,readinessDimension:"工作模擬與溝通"}),
    ],
  },
];

const questions = chapters.flatMap((chapter) => chapter.questions);
const questionById = new Map(questions.map((item) => [item.id, item]));

export function getQuestion(questionId) {
  return questionById.get(questionId) ?? null;
}

export function getQuestions() {
  return questions;
}

export function getChapters() {
  return chapters;
}

export function publicQuestion(item) {
  const { referenceSql: _referenceSql, compare: _compare, ordered: _ordered, ...safe } = item;
  return safe;
}
